CREATE TABLE IF NOT EXISTS auth (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    token VARCHAR(500) NOT NULL UNIQUE,
    expires_in INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);